python multitest.py \
--gpu_ids='1' \
--test_dir='/home/share/ziyi/data/DukeMTMC-reID/' \
--namesmall='/home/ziyi/Desktop/dukesmallr3again' \
--namelarge='/home/ziyi/Desktop/dukelarger3' \
--which_epochsmall='99' \
--which_epochlarge='99' \
--batchsize='32' \
--img_h='384' \
--img_w='128' \
--img_h2='576' \
--img_w2='192'
